### ISSUE TITLE
Feature request: Make API docs curl friendly

### ISSUE THREAD

**Issue by pieterhouwen** [gotify/api-docs#1]
Hello,

I'm writing a wrapper script which will automatically setup and configure a Gotify instance and give it some tasks but I'm not sure how to do it with JSON tokens on the command line, 

The example with curl at: https://gotify.net/docs/pushmsg works beautifully for me but I'm not sure how to continue with curl looking at the rest of the documentation. I can see a dropdown menu where I can select the parameter content type I would like to see but that only has application/json as an option.

Can you add a howto using curl?

**Comment by jmattheis** [comment]
When using our api documentation, you can see curl examples:
![image](https://user-images.githubusercontent.com/14895212/98164551-602afb00-1edc-11eb-9bda-b5e068ac586e.png)

You can use [gotify/cli](https://github.com/gotify/cli) and push the message like this `gotify push --contentType text/markdown "My Message"` if you want something simple to use.

**Comment by pieterhouwen** [comment]
Thanks for your reply, I did not notice the "Try it out" button which expanded the view to also include curl examples, thanks for the tip.

I will have a look at the gotify/cli project :)


Thanks again!
